### ISSUE TITLE
NullreferenceException in NestedMarkupExtension because WeakReferenc<>.IsAlive

### ISSUE THREAD

**Issue by PFriedland89** [MrCircuit/XAMLMarkupExtensions#8]
Got this error reproduced in our software. There is already a known, solved issue in WpfLocalizationExtension in commit 06fba0b7547bbbcfbf87bd31a403faa440e44452 for a different method. This is my stacktrace:

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XAMLMarkupExtensions.Base.NestedMarkupExtension.EndpointReachedEvent.AddListener(NestedMarkupExtension listener)
   at XAMLMarkupExtensions.Base.NestedMarkupExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   at System.Xaml.XamlObjectWriter.Logic_ProvideValue(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.Logic_AssignProvidedValue(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteEndObject()
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Views.TestView.StatusView.InitializeComponent() in e:\work\workspace\test\TestView.xaml:line 1
   at Views.TestView.StatusView..ctor() ine:\work\workspace\test\TestView.xaml.cs:line 14
```

It seems to be a problem in NestedMarkupExtension.EndpointReachedEvent.AddListener. The weak reference is accessed using IsAlive, which is bad and can occur in rare cases to NullReferenceExceptions as I got.

**Comment by SeriousM** [comment]
Hi @PFriedland89,

I checked the method [`NestedMarkupExtension.EndpointReachedEvent.AddListener`](https://github.com/MrCircuit/XAMLMarkupExtensions/blob/4733b27f926074c2a3f78ad79e8d24b93160cae6/XAMLMarkupExtensions/Base/NestedMarkupExtension.cs#L694-L728) but there is no `.IsAlive` call and the WeakReference usage looks good to me...

@MrCircuit, could you have a look at it? Is the latest version released?

**Comment by PFriedland89** [comment]
Thank you for your fast answer, you're deadly right. But I am a bit confused that I have the wrong code. I habe the XamlMarkupExtension 1.20 trough nuget and the assemlby contains the old code with the wrong IsAlive usage (checked it with ILSpy). I use the .NET 4 assembly. Any idea?

**Comment by SeriousM** [comment]
> EDIT: I have to mention I use WpfLocalizationExtension, may this introduce a XamlMarkupExtension with same version but different code as WpfLocalizationExtension depends on XAMLMarkupExtension?

The WpfLocalizeExtension depends on `XAMLMarkupExtensions (>= 1.2.1.3)` which is lower than `1.20.x`. Please try to update the XamlMarkupExtension manual to the latest version and verify the behavior. I guess we need to update the WpfLocalizeExtension dependency then.

Thank you!

**Comment by PFriedland89** [comment]
Manually updating XamlMarkupExtension in Nuget solves this issue, great! But please increase the minimum required version in nuget, this is a really bad error for commecial projects.

**Comment by SeriousM** [comment]
> this is a really bad error for commecial projects

may I ask what's the project name? just curious who's using the extension.

**Comment by PFriedland89** [comment]
I think I am not allowed to tell you the name of the product. But it is used a medical system for a dynamic localization library in WPF client software.

**Comment by SeriousM** [comment]
> But it is used a medical system for a dynamic localization library in WPF client software.

oh cool, that means that someone could die if the extension does not work as expected in critical situations... we need more tests :)

**Comment by PFriedland89** [comment]
Oh no, of course not as this is as said the client only software ;). but stable software is very important for the customers, so upcoming issues already solved are the best ones.
